### ISSUE TITLE
Lnk

### ISSUE THREAD

**Issue by johnjohnsp1** [Allevon412/AssaultCubeCheatEngine#1]
Hi,
thanks for sharing the code, actually i compile it with VStudio2022 on a windows 10 machine and getting this error:

Error | LNK1120 | 1 unresolved externals | ACTrainer | C:\temp\AssaultCubeCheatEngine\ACTrainer\x64\Release\ACTrainer.exe | 1 |  
Error | LNK2001 | unresolved external symbol main | ACTrainer | C:\temp\AssaultCubeCheatEngine\ACTrainer\ACTrainer\MSVCRT.lib(exe_main.obj) | 1 |  

i do something wrong or miss anything ? 
the version of the software i use are:

Windows 10 22H2 Build 19045.3208
and
Microsoft Visual Studio Community 2022
Version 17.6.4
VisualStudio.17.Release/17.6.4+33815.320
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Community
Visual C++ 2022   00482-90000-00000-AA404
Microsoft Visual C++ 2022
ASP.NET and Web Tools   17.6.326.62524
ASP.NET and Web Tools
Azure App Service Tools v3.0.0   17.6.326.62524
Azure App Service Tools v3.0.0
C# Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Cookiecutter   17.0.23087.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.
Dotfuscator Community Edition   6.5.3+7f0b0a9d18
PreEmptive Protection - Dotfuscator CE
Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
NuGet Package Manager   6.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
Python - Profiling support   17.0.23087.1
Profiling support for Python projects.
Python with Pylance   17.0.23087.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.
Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.
Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.
Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.
TypeScript Tools   17.0.20329.2001
TypeScript Tools for Microsoft Visual Studio
Visual Basic Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Visual F# Tools   17.6.0-beta.23174.5+0207bea1afae48d9351ac26fb51afc8260de0a97
Microsoft Visual F# Tools
Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by Allevon412** [comment]
It's most likely the fact you're attempting to compile the code as an exe when it's in-fact a dll. There should be no main function because there isn't one. If you're telling VS to compile as an exe it will look to link / compile the main func. But since its a dll only the DLLMain func exists. Additionally, in the release folder there is a compiled version of the code.
